# Generated by Django 6.0 on 2026-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_create_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EXECUTIVE', 'Ejecutivo'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10),
        ),
    ]
