# Generated by Django 6.0 on 2026-03-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Petición'), ('Q', 'Queja'), ('R', 'Reclamo'), ('S', 'Sugerencia')], max_length=1)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=10)),
            ],
        ),
    ]
