# Generated by Django 6.0 on 2026-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
