# Generated by Django 6.0 on 2026-02-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOTES', '0002_create_default_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='lot_images/'),
        ),
    ]
