# Generated by Django 6.0 on 2026-02-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOTES', '0005_fix_stages_for_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
