# Generated by Django 6.0 on 2026-02-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALES', '0003_sync_lot_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
