# Generated by Django 6.0 on 2026-02-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALES', '0004_purchase_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
